#### JOB SCRIPT SETTINGS ####

#@ SBATCH --time=00:30:00
#@ SBATCH --partition=standard-g
#@ container=base-torch2.3.0-rocm6.0.3_20251016.sif
#@ venv=core-531546e
#@ rmi_plot_config=default_CERRA_plot.yaml

# Anemoi-graphs config

nodes:
  # Data nodes
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        cutout:
          - dataset: /scratch/project_465002133/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-rmi.zarr
          - dataset: /scratch/project_465002133/datasets/aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
        min_distance_km: 0
        adjust: all
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.UniformWeights # options: Area, Uniform
        norm: unit-max # options: l1, l2, unit-max, unit-sum, unit-std
      cutout:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
      boundary:
        _target_: anemoi.graphs.nodes.attributes.BooleanNot
        masks: 
          _target_: anemoi.graphs.nodes.attributes.CutOutMask
  # Hidden nodes
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes # options: ZarrDatasetNodes, NPZFileNodes, TriNodes
      resolution: 9 # grid resolution for npz (o32, o48, ...)
      reference_node_name: data
      mask_attr_name: cutout
      margin_radius_km: 600 #(default is 100km)

edges:
# Encoder configuration
- source_name: data
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 12
    source_mask_attr_name: cutout
  - _target_: anemoi.graphs.edges.CutOffEdges # connects only boundary nodes
    cutoff_factor: 4 # only for cutoff method
    source_mask_attr_name: boundary
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
# Processor configuration
- source_name: hidden
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
    scale_resolutions: 9
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
# Decoder configuration
- source_name: hidden
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    target_mask_attr_name: cutout
    num_nearest_neighbours: 3
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors:
  - _target_: anemoi.graphs.processors.RestrictEdgeLength
    source_name: data
    target_name: hidden
    max_length_km: 20
    source_mask_attr_name: cutout
      
  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: data
    ignore: cutout # optional
    save_mask_indices_to_attr: indices_connected_nodes # optional